#%RAML 0.8
displayName: GpsrInfo
get:
  description: Returns all GPSR picogramms and safety statements from the shop. *epages6 *epagesNow
  responses:
    200:
      body:
        application/json:
          example: !include examples/get_gpsrinfo_response.json
          schema: !include schema/get_gpsrinfo.schema.json
