FROM ruby:2.1

#####################
# Configure basics. #
#####################

# Configure timezone server
ENV TZ 'Europe/Berlin'
RUN echo "${TZ}" | tee /etc/timezone \
  && dpkg-reconfigure --frontend noninteractive tzdata

# Grab gosu for easy step-down from root
RUN gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4
RUN arch="$(dpkg --print-architecture)" \
	&& set -x \
	&& curl -o /usr/local/bin/gosu -fSL "https://github.com/tianon/gosu/releases/download/1.3/gosu-$arch" \
	&& curl -o /usr/local/bin/gosu.asc -fSL "https://github.com/tianon/gosu/releases/download/1.3/gosu-$arch.asc" \
	&& gpg --verify /usr/local/bin/gosu.asc \
	&& rm /usr/local/bin/gosu.asc \
	&& chmod +x /usr/local/bin/gosu

##################################
# Setup epages-docs environment. #
##################################

ENV EPAGES_DOCS=/usr/src/epages-docs

# Create the epages-docs dir 
RUN mkdir -p ${EPAGES_DOCS}
WORKDIR ${EPAGES_DOCS}

# Install gems
COPY Gemfile Gemfile.lock ${EPAGES_DOCS}/
RUN  bundle install

# Copy repo to enable running without the mounted volume.
# COPY . ${EPAGES_DOCS}

# Set mountpoint
VOLUME ${EPAGES_DOCS}

# Copy our entrypoint script
COPY _docker/docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["rake"]