nginx:
  image: docker.epages.com/epages/docs-nginx:stable
  links:
    - "elasticsearch:elasticsearch"
  ports:
    - "8080:80"

elasticsearch:
  image: docker.epages.com/epages/docs-elasticsearch:stable
