#%RAML 0.8
displayName: Token
description: Retrieve the OAuth2 token for the client.
post:
  description: Creates the OAuth2 token for the client.
  body:
    application/x-www-form-urlencoded:
      formParameters:
        client_id:
          description: The OAuth2 client_id.
          required: true
          #type: file
        client_secret:
          description: The OAuth2 client_secret.
          required: true
        code:
          description: The OAuth2 authorisation code.
          required: true
  responses:
    200:
      description: The OAuth2 access token.
      body:
        application/vnd.epages.v1+json:
          example: |
            {
                "access_token" : "ABCDEF0124"
            }
