#%RAML 0.8
  displayName: Locale information
  description: Retrieve the locale information of a shop.
  get:
    description: Returns the shop's locale information, i.e. the language identifier and the region identifier. *epages6 *epagesNow
    securedBy: [products_read]
    responses:
      200:
        body:
          application/json:
            example: !include examples/get_locale_response.json
            schema: !include schema/get_locale.schema.json
