#%RAML 0.8
displayName: Product Export
description: Exports a collection of all products of a shop in a CSV file.
get:
  description: Returns a CSV file with all products of the shop.
  securedBy: [products_read_batch]
  is: [ locale ]
  responses:
    200:
      body:
        text/csv:
          example: !include examples/product_portal_response.csv
