#%RAML 0.8
  displayName: Categories
  description: A collection of product categories of a shop.
  get:
    description: |
        Returns the product categories of the shop. This usually is the default root category "Categories",
        but can also include additional root categories, if supported by the shop.
    securedBy: [products_read]
    is: [ locale ]
    responses:
      200:
        body:
          application/json:
            example: !include examples/get_categories_response.json
            schema: !include schema/get_categories.schema.json

  /{categoryId}:
      displayName: Category ID
      description: The unique identifier of the category.
      get:
        description: Returns the category identified by the provided category ID.
        securedBy: [products_read]
        is: [ locale ]
        responses:
          200:
            body:
              application/json:
                example: !include examples/get_categories_categoryid_response.json
                schema: !include schema/get_categories_categoryid.schema.json
      put:
        description: Modifies a category.
        securedBy: [products_write]
        is: [ locale ]
        body:
          application/json:
            example: !include examples/put_categories_categoryid_request.json
        responses:
          200:
            body:
              application/json:
                example: !include examples/put_categories_categoryid_response.json
                schema: !include schema/put_categories_categoryid.schema.json
