#%RAML 0.8
displayName: Legal information
description: Summary of legal information for a shop.
get:
  description: Returns hyperlinks of legal information for a shop.
  is: [ locale ]
  responses:
    200:
      body:
        application/json:
          example: !include examples/get_legal_response.json
          schema: !include schema/get_legal.schema.json
/contact-information:
  displayName: Contact information
  description: The contact information of a shop.
  get:
    description: Returns the contact information of a shop.
    is: [ locale ]
    responses:
      200:
        body:
          application/json:
            example: !include examples/get_legal_contact_response.json
            schema: !include schema/get_legal_contact.schema.json
  put:
    description: Modifies the contact information of a shop.
    is: [ localeMandatory ]
    body:
      application/json:
        example: !include examples/put_legal_contact_response.json
    responses:
      200:
        body:
          application/json:
            example: !include examples/put_legal_contact_response.json

/privacy-policy:
    displayName: Privacy policy
    description: Retrieve the privacy policy of a shop.
    get:
      description: Returns the privacy policy of a shop.
      is: [ locale ]
      responses:
        200:
          body:
            application/json:
              example: !include examples/get_legal_privacy_response.json

    put:
      description: Modifies the privacy policy of a shop.
      is: [ localeMandatory ]
      body:
        application/json:
          example: !include examples/put_legal_privacy_response.json
      responses:
        200:
          body:
            application/json:
              example: !include examples/put_legal_privacy_response.json

/terms-and-conditions:
  displayName: Terms and conditions
  description: The terms and conditions of a shop.
  get:
    description: Returns the terms and conditions of a shop.
    is: [ locale ]
    responses:
      200:
        body:
          application/json:
            example: !include examples/get_legal_terms_response.json
  put:
    description: Modifies the terms and conditions of a shop.
    is: [ localeMandatory ]
    body:
      application/json:
        example: !include examples/put_legal_terms_response.json
    responses:
      200:
        body:
          application/json:
            example: !include examples/put_legal_terms_response.json

/rights-of-withdrawal:
    displayName: Rights of withdrawal
    description: Retrieve the rights of withdrawal of a shop.
    get:
      description: Returns the customer rights of withdrawal of a shop.
      is: [ locale ]
      responses:
        200:
          body:
            application/json:
              example: !include examples/get_legal_rights_response.json
    put:
      description: Modifies the customer rights of withdrawal of a shop.
      is: [ localeMandatory ]
      body:
        application/json:
          example: !include examples/put_legal_rights_response.json
      responses:
        200:
          body:
            application/json:
              example: !include examples/put_legal_rights_response.json

/shipping-information:
    displayName: Shipping information
    description: Retrieve the shipping terms and information of a shop.
    get:
      description: Returns detailed information about possible shipping types and the costs incurred. Also displays the costs for shipment abroad.
      is: [ locale ]
      responses:
        200:
          body:
            application/json:
              example: !include examples/get_legal_shipping_response.json

    put:
      description: Modifies the shipping information of a shop.
      is: [ localeMandatory ]
      body:
        application/json:
          example: !include examples/put_legal_shipping_response.json
      responses:
        200:
          body:
            application/json:
              example: !include examples/put_legal_shipping_response.json
