#%RAML 0.8
displayName: Legal information
get:
  description: Returns hyperlinks of legal information for a shop. *epages6 *epagesNow
  securedBy: [legal_read]
  is: [ locale ]
  responses:
    200:
      body:
        application/json:
          example: !include examples/get_legal_response.json
          schema: !include schema/get_legal.schema.json
/contact-information:
  displayName: Contact information
  get:
    description: Returns the contact information of a shop. *epages6
    securedBy: [legal_read]
    is: [ locale ]
    responses:
      200:
        body:
          application/json:
            example: !include examples/get_legal_contact_response.json
            schema: !include schema/get_legal_contact.schema.json
  put:
    description: Modifies the contact information of a shop. *epages6
    securedBy: [legal_write]
    is: [ localeMandatory ]
    body:
      application/json:
        example: !include examples/put_legal_contact_request.json
        schema: !include schema/put_legal_contact_request.schema.json
    responses:
      200:
        body:
          application/json:
            example: !include examples/put_legal_contact_response.json
            schema: !include schema/put_legal_contact.schema.json

/privacy-policy:
    displayName: Privacy policy
    get:
      description: Returns the privacy policy of a shop. *epages6
      securedBy: [legal_read]
      is: [ locale ]
      responses:
        200:
          body:
            application/json:
              example: !include examples/get_legal_privacy_response.json
              schema: !include schema/get_legal_privacy.schema.json

    put:
      description: Modifies the privacy policy of a shop. *epages6
      securedBy: [legal_write]
      is: [ localeMandatory ]
      body:
        application/json:
          example: !include examples/put_legal_privacy_request.json
          schema: !include schema/put_legal_privacy_request.schema.json
      responses:
        200:
          body:
            application/json:
              example: !include examples/put_legal_privacy_response.json
              schema: !include schema/put_legal_privacy.schema.json

/terms-and-conditions:
  displayName: Terms and conditions
  get:
    description: Returns the terms and conditions of a shop. *epages6
    securedBy: [legal_read]
    is: [ locale ]
    responses:
      200:
        body:
          application/json:
            example: !include examples/get_legal_terms_response.json
            schema: !include schema/get_legal_terms.schema.json
  put:
    description: Modifies the terms and conditions of a shop. *epages6
    securedBy: [legal_write]
    is: [ localeMandatory ]
    body:
      application/json:
        example: !include examples/put_legal_terms_request.json
        schema: !include schema/put_legal_terms_request.schema.json
    responses:
      200:
        body:
          application/json:
            example: !include examples/put_legal_terms_response.json
            schema: !include schema/put_legal_terms.schema.json

/rights-of-withdrawal:
    displayName: Rights of withdrawal
    get:
      description: Returns the customer rights of withdrawal of a shop. *epages6
      securedBy: [legal_read]
      is: [ locale ]
      responses:
        200:
          body:
            application/json:
              example: !include examples/get_legal_rights_response.json
              schema: !include schema/get_legal_rights.schema.json
    put:
      description: Modifies the customer rights of withdrawal of a shop. *epages6
      securedBy: [legal_write]
      is: [ localeMandatory ]
      body:
        application/json:
          example: !include examples/put_legal_rights_request.json
          schema: !include schema/put_legal_rights_request.schema.json
      responses:
        200:
          body:
            application/json:
              example: !include examples/put_legal_rights_response.json
              schema: !include schema/put_legal_rights.schema.json

/shipping-information:
    displayName: Shipping information
    get:
      description: Returns detailed information on possible shipping types and the costs incurred. Also displays the costs for shipment abroad. *epages6
      securedBy: [legal_read]
      is: [ locale ]
      responses:
        200:
          body:
            application/json:
              example: !include examples/get_legal_shipping_response.json
              schema: !include schema/get_legal_shipping.schema.json

    put:
      description: Modifies the shipping information of a shop. *epages6
      securedBy: [legal_write]
      is: [ localeMandatory ]
      body:
        application/json:
          example: !include examples/put_legal_shipping_request.json
          schema: !include schema/put_legal_shipping_request.schema.json
      responses:
        200:
          body:
            application/json:
              example: !include examples/put_legal_shipping_response.json
              schema: !include schema/put_legal_shipping.schema.json
