#%RAML 0.8
  displayName: Resource for locale support
  is: [ base ]
  get:
    description: The shop locale information resource
    responses:
      404:
        description: Shop not found
      200:
        body:
          application/json:
            example: |
              {
              "default" : "de_DE",
              "items":
                    [
                        "de_DE", "en_US"
                    ]
              }
