#%RAML 0.8
displayName: Product and category assignment
post:
  description: Assigns categories to products and products to categories.
  securedBy: [products_write]
  body:
    application/x-www-form-urlencoded:
      formParameters:
        categoryId:
          description: The category to be assigned for the defined products. Can be one or more categories.
          required: true
          type: string
        productId:
          description: The product to be assigned to the defined category. Can be one or more products.
          required: true
          type: string
  responses:
    204:

delete:
  description: Deletes one or more products from a category.
  securedBy: [products_write]
  responses:
    204:
