#%RAML 0.8
displayName: Orders
description: Orders of the shop.
get:
  description: Returns a list of orders.
  is: [ locale ]
  responses:
    200:
      body:
        application/json:
          example: |
            {}
/{orderId}:
  displayName: Order
  description: Returns the order by orderId.
  get:
    description: Returns the order by orderId.
    is: [ locale ]
    responses:
      200:
        body:
          application/json:
            example: !include examples/order_response.json
  put:
    description: Updates the order
    is: [ locale ]
    body:
      application/json:
        example: !include examples/order_response.json
    responses:
      204: