#%RAML 0.8
  displayName: Public information
  description: The public information associated with the shop.
  get:
    description: Returns the public information of a shop, like name, slogan and logo.
    is: [ locale ]
    responses:
      404:
        description: Not Found
      200:
        body:
          application/json:
            example: |
              {
                "name" : "Milestones",
                "slogan" : "gut_geruestet_für_Ihre_Ziele",
                "logo" : {
                    "url": "http://epagesj-vm02/WebRoot/Store/Shops/DemoShop/Logo.gif",
                    "classifier" : "Small"
                }
              }

  post:
    description: Creates the complete public information of the shop.
    body:
           application/vnd.epages.complete.v1+json:
             example: |
              {
                 names  : {
                   "de" : "Milestones",
                   "en" : "Milestones"
                 },
                 slogans : {
                   "de" : "gut_geruestet_für_Ihre_Ziele",
                   "en" : "Good to meet your goals"
                 },
                 "logo" : {
                    "url": "http://epagesj-vm02/WebRoot/Store/Shops/DemoShop/Logo.gif",
                    "classifier" : "Small"
                }
              }
    responses:
      200:
        description: OK
