#%RAML 0.8
  displayName: Currency information of the shop
  get:
    description: Returns the currency information of a shop.
    responses:
      404:
        description: Not Found
      200:
        body:
          application/json:
            example: |
              {
              "default" : "EUR",
              "items":
                    [
                        "EUR", "USD", "GBP"
                    ]
              }
