#%RAML 0.8
  displayName: Currency information
  description: Retrieve the currency information of a shop.
  get:
    description: Returns the currency information of a shop. *epages6 *epagesNow
    securedBy: [products_read]
    responses:
      200:
        body:
          application/json:
            example: !include examples/get_currency_response.json
            schema: !include schema/get_currency.schema.json
