/weights/{shopGUID}:
  description: Weights Resource for popularity search
  uriParameters:
    shopGUID:
      description: the shop guid
      example: 50589501-89A6-02BC-D76C-AC15800C847C
  get:
    description: gets the weights used for sorting by popularity
    responses:
      200:
        body:
          application/json:
            example: !include popularity_weight_output.json
      404:
        description: Search popularity weighting not found.
  put:
    description: Sets the weights used for sorting by popularity
    body: 
      application/json:
        example: !include popularity_weight_input.json
    responses:
      200:
        body:
          application/json:
            example: !include popularity_weight_output.json
      400:
        body:
          text/plain:
            example: |
              averageNumberOfSales must be between 0 and 10 (path = WeightingResource.setWeights.arg1.averageNumberOfSales, invalidValue = 20)
  delete:
    description: Deletes the weights used for sorting by popularity
    responses:
      204: