#%RAML 0.8
---
title: ePages Public REST API
baseUri: https://developer.epages.com/api
version: v1

securedBy: [OAuth_2.0_Token,oauth_1_0]

securitySchemes:
    - OAuth_2.0_Token:
        type: x-custom
        description: OAuth 2.0 token authentication
        describedBy:
          headers:
            Authorization:
              type: string
              required: true
              example: "Bearer "
              pattern: ^Bearer .+
    - oauth_1_0:
        description:
            OAuth 1.0 authentification.
        type: OAuth 1.0
        settings:
          requestTokenUri: /rs/oauth1/request_token
          authorizationUri: /rs/oauth1/authorize
          tokenCredentialsUri: /rs/oauth1/access_token

traits: !include traits.raml

/shops/{shopId}:
  uriParameters:
    shopId:
      description: The unique identifier of the shop.
      example: DemoShop
  /products: !include product/product.raml
  /categories: !include category/category.raml
  /carts: !include cart/cart.raml
  /legal: !include legal/legal.raml
  /locales: !include locale/locale.raml
  /public-info: !include public-info/public-info.raml
  /currencies: !include currency/currency.raml
  /search: !include search/search.raml
  /shipping-methods: !include shipping-method/shipping-method.raml
  /start-page: !include start-page/start-page.raml
  /token: !include appstore/token.raml
