- locale:
    queryParameters:
      locale:
        description: Represents the language code according to ISO 639-1 and the country code according to ISO 3166-1.
        example: en_US
        required : false
- currency:
    queryParameters:
      currency:
        description: Represents the currency code according to ISO 4217.
        example: EUR
- paged:
    queryParameters:
      page:
        description: Represents the current page.
        type: integer
        minimum: 1
        default: 1
      resultsPerPage:
        description: Specifies the maximum number of results per page.
        type: integer
        minimum: 10
        default: 10
- direction:
    queryParameters:
      direction:
        description: Specifies the sorting direction, which can be either ascending or descending.
        enum: [asc, desc]
