- locale:
    queryParameters:
      locale:
        description: Represents the language code according to ISO 639-1 and the country code according to ISO 3166-1. If not provided, the shop's default language is used. We recommend to always send this parameter with your request. If the default language had been changed in the administration, it might take up to 1 day until this change affects the shop.
        example: en_US
        required : false
- localeMandatory:
    queryParameters:
      locale:
        description: Represents the language code according to ISO 639-1 and the country code according to ISO 3166-1.
        example: en_US
        required : true
- currency:
    queryParameters:
      currency:
        description: Represents the currency code according to ISO 4217.
        example: EUR
- paged:
    queryParameters:
      page:
        description: Represents the current page.
        type: integer
        minimum: 1
        default: 1
      resultsPerPage:
        description: Specifies the maximum number of results per page.
        type: integer
        default: 10
        maximum: 100
- direction:
    queryParameters:
      direction:
        description: Specifies the sorting direction, which can be either ascending or descending.
        enum: [asc, desc]
