#%RAML 0.8
displayName: Start page
description: Products assigned to the start page of a shop.
/products:
  displayName: Products
  description: Retrieve all products assigned to the start page.
  get:
    description: Returns a list of all products on the start page.
    is: [ locale, currency, paged ]
    queryParameters:
    responses:
      200:
        body:
          application/json:
            example: !include ../product/get_products_response.json
