#%RAML 0.8
displayName: Carts
description: Operations on the carts of a shop.
post:
  description: Creates a cart for a shop.
  body:
    application/json:
      example: !include examples/input_cart.json
  responses:
    201:
      body:
        application/json:
          example: !include examples/post_carts_response.json
          schema: !include schema/post_carts.schema.json

/{cartId}:
  displayName: Cart ID
  description: Retrieve a specific cart using its ID.
  get:
    description: Returns a specified cart from a shop.
    responses:
      200:
        body:
          application/json:
            example: !include examples/get_carts_cartid_response.json
            schema: !include schema/get_carts_cartid.schema.json

  /line-items:
    displayName: Line items
    description: The line items of a product within a cart.
    post:
      description: Creates a product line item in a cart.
      body:
        application/json:
          example: |
            {
              "productId": "prodGUID",
              "quantity": 1
            }
      responses:
        201:
          body:
            application/json:
              example: !include examples/post_carts_cartid_lineitem_response.json
              schema: !include schema/post_carts_cartid_lineitem.schema.json

    /{lineItemId}:
      displayName: Line item ID
      description: The unique identifier of the product line item.
      put:
        description: Modifies a specified product line item in a cart.
        body:
          application/json:
            example: |
              {
                  "quantity": 3
              }
        responses:
          200:
            body:
              application/json:
                example: !include examples/put_carts_cartid_lineitem_itemid_response.json
                schema: !include schema/put_carts_cartid_lineitem_itemid.schema.json
      delete:
        description: Deletes a specified product line item from a cart.
        responses:
          200:
            body:
              application/json:
                example: !include examples/delete_carts_cartid_lineitem_itemid_response.json
                schema: !include schema/delete_carts_cartid_lineitem_itemid.schema.json

  /billing-address:
    displayName: Billing address
    description: The billing address a cart requires.
    put:
      description: Modifies the billing address for a cart.
      body:
        application/json:
          example: !include examples/input_address.json
      responses:
        200:
          body:
            application/json:
              example: !include examples/put_carts_cartid_billing_response.json
              schema: !include schema/put_carts_cartid_billing.schema.json
        400:
          body:
            application/json:
              example: !include examples/put_carts_cartid_billing_response400.json
    delete:
      description: Deletes the billing address from a cart.
      responses:
        200:
          body:
            application/json:
              example: !include examples/delete_carts_cartid_billing_response.json
              schema: !include schema/delete_carts_cartid_billing.schema.json

  /shipping-address:
    displayName: Shipping address
    description: The shipping address a cart requires.
    put:
      description: Modifies the shipping address for a cart.
      body:
        application/json:
          example: !include examples/input_address.json
      responses:
        200:
          body:
            application/json:
              example: !include examples/put_carts_cartid_shipping_response.json
              schema: !include schema/put_carts_cartid_shipping.schema.json
        400:
          body:
            application/json:
              example: !include examples/put_carts_cartid_shipping_response400.json
    delete:
      description: Deletes the shipping address from a cart.
      responses:
        200:
          body:
            application/json:
              example: !include examples/delete_carts_cartid_shipping_response.json
              schema: !include schema/delete_carts_cartid_shipping.schema.json
