#%RAML 0.8
displayName: Carts
description: Operations on the carts of a shop.
post:
  description: Creates a cart for a shop.
  body:
    application/json:
      example: !include examples/input_cart.json
  responses:
    201:
      body:
        application/json:
          example: !include examples/response.json

/{cartId}:
  displayName: Cart ID
  description: Retrieve a specific cart using its ID.
  get:
    description: Returns a specified cart from a shop.
    responses:
      200:
        body:
          application/json:
            example: !include examples/response.json

  /line-items:
    post:
      description: Creates an item in a cart.
      body:
        application/json:
          example: |
            {
              "productId": "prodGUID",
              "quantity": 1
            }
      responses:
        201:
          body:
            application/json:
              example: !include examples/response.json

    /{lineItemId}:
      put:
        description: Modifies a specified line item in a cart.
        body:
          application/json:
            example: |
              {
                  "quantity": 3
              }
        responses:
          200:
            body:
              application/json:
                example: !include examples/response.json
      delete:
        description: Deletes a specified line item from a cart.
        responses:
          200:
            body:
              application/json:
                example: !include examples/response.json

  /billing-address:
    put:
      description: Modifies the billing address for a cart.
      body:
        application/json:
          example: !include examples/input_address.json
      responses:
        200:
          body:
            application/json:
              example: !include examples/response.json
        400:
          body:
            application/json:
    delete:
      description: Deletes the billing address for a cart.
      responses:
        200:
          body:
            application/json:
              example: !include examples/response.json
        400:
          body:
            application/json:

  /shipping-address:
    put:
      description: Modifies the shipping address for a cart.
      body:
        application/json:
          example: !include examples/input_address.json
      responses:
        200:
          body:
            application/json:
              example: !include examples/response.json
        400:
          body:
            application/json:
    delete:
      description: Deletes the shipping address for a cart.
      responses:
        200:
          body:
            application/json:
              example: !include examples/response.json
        400:
          body:
            application/json:
