#%RAML 0.8
displayName: Carts
post:
  description: Creates a cart for a shop.
  securedBy: [products_read]
  body:
    application/json:
      example: !include examples/post_carts_request.json
  responses:
    201:
      body:
        application/json:
          example: !include examples/post_carts_response.json
          schema: !include schema/post_carts.schema.json

/{cartId}:
  displayName: Cart
  get:
    description: Returns a specific cart from a shop identified by the provided cart ID.
    securedBy: [carts_read]
    responses:
      200:
        body:
          application/json:
            example: !include examples/get_carts_cartid_response.json
            schema: !include schema/get_carts_cartid.schema.json

  /line-items:
    displayName: Line items
    post:
      description: Creates a product line item in a cart.
      securedBy: [carts_write]
      body:
        application/json:
          example: !include examples/post_carts_cartid_lineitem_request.json
      responses:
        201:
          body:
            application/json:
              example: !include examples/post_carts_cartid_lineitem_response.json
              schema: !include schema/post_carts_cartid_lineitem.schema.json

    /{lineItemId}:
      displayName: Line item
      put:
        description: Modifies a specific product line item in a cart.
        securedBy: [carts_write]
        body:
          application/json:
            example: !include examples/put_carts_cartid_lineitem_itemid_request.json
        responses:
          200:
            body:
              application/json:
                example: !include examples/put_carts_cartid_lineitem_itemid_response.json
                schema: !include schema/put_carts_cartid_lineitem_itemid.schema.json
      delete:
        description: Deletes a specific product line item from a cart.
        securedBy: [carts_write]
        responses:
          200:
            body:
              application/json:
                example: !include examples/delete_carts_cartid_lineitem_itemid_response.json
                schema: !include schema/delete_carts_cartid_lineitem_itemid.schema.json

  /billing-address:
    displayName: Billing address
    put:
      description: Modifies the billing address for a cart.
      securedBy: [carts_write]
      body:
        application/json:
          example: !include examples/put_carts_cartid_billing_request.json
      responses:
        200:
          body:
            application/json:
              example: !include examples/put_carts_cartid_billing_response.json
              schema: !include schema/put_carts_cartid_billing.schema.json
    delete:
      description: Deletes the billing address from a cart.
      securedBy: [carts_write]
      responses:
        200:
          body:
            application/json:
              example: !include examples/delete_carts_cartid_billing_response.json
              schema: !include schema/delete_carts_cartid_billing.schema.json

  /shipping-address:
    displayName: Shipping address
    put:
      description: Modifies the shipping address for a cart.
      securedBy: [carts_write]
      body:
        application/json:
          example: !include examples/put_carts_cartid_shipping_request.json
      responses:
        200:
          body:
            application/json:
              example: !include examples/put_carts_cartid_shipping_response.json
              schema: !include schema/put_carts_cartid_shipping.schema.json
    delete:
      description: Deletes the shipping address from a cart.
      securedBy: [carts_write]
      responses:
        200:
          body:
            application/json:
              example: !include examples/delete_carts_cartid_shipping_response.json
              schema: !include schema/delete_carts_cartid_shipping.schema.json
