#%RAML 0.8
  displayName: Categories
  is:
  get:
    description: Returns the categories of a shop.
    is:
    responses:
      200:
        body:
          application/json:
            example:
      404:
        body:
          application/json:
            example:
      503:
        body:
          application/json:
            example:
